### PR TITLE
Documentation: set of example cards

### PR DESCRIPTION
**Pull request by vingerha**
Initial set of cards based on eleve 'parent fanny'

### CODE REVIEW

**Comment by Anas92230** [comment]
Hi,
thank you for this work. did you used a specific css? because on my interface I don't see your result. for example the card on grades data it's not fit.
thanks for your help

**Comment by vingerha** [comment]
Nothing special that I am aware of, I have no clue if things were installed with other cards but I doubt(!) this to be the case as also with the Dathosim setup all seems in line

**Comment by Anas92230** [comment]
I found! now all it's ok :-) I had to install card-mod from hacs...

**Comment by Anas92230** [comment]
Hello
I have errors on timetable :
Example today is 06 july:
- for sensor timetable_today I have data for 05 july
- for sensor timetable_tomorrow data for 6 july
-for sensor timetable_next_day I have data for 7 july.
Do you have any suggestion?
Thanks

**Pull request closed without merging**
